name: url_launcher
description: Flutter plugin for launching a URL. Supports
  web, phone, SMS, and email schemes.
repository: https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+url_launcher%22
version: 6.3.1
publish_to: none

environment:
  sdk: ^3.0.6
  flutter: ">=3.10.6"

flutter:
  plugin:
    platforms:
      android:
        default_package: url_launcher_android
      ios:
        default_package: url_launcher_ios

dependencies:
  flutter:
    sdk: flutter
  url_launcher_android:
    git:
      url: https://github.com/fadlurahmanfdev/packages.git
      ref: url_launcher_android-v6.3.12-bebas
      path: packages/url_launcher/url_launcher_android
  url_launcher_ios:
    git:
      url: https://github.com/fadlurahmanfdev/packages.git
      ref: url_launcher_ios-v6.3.1-bebas
      path: packages/url_launcher/url_launcher_ios
  url_launcher_platform_interface:
    git:
      url: https://github.com/fadlurahmanfdev/packages.git
      ref: v2.3.2-bebas
      path: packages/url_launcher/url_launcher_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  plugin_platform_interface: ^2.1.7
  test: ^1.16.3

topics:
  - links
  - os-integration
  - url-launcher
  - urls
